version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_AUTH_DB}
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet

  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb
      MONGO_DATABASE: csv_visualization_demo
      MONGO_AUTH_DB: ${MONGO_AUTH_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    command: mvn clean spring-boot:run
    depends_on:
      - mongodb

